<?xml version="1.0"?>
<package format="3">
  <name>ur_description</name>
  <version>1.3.0</version>
  <description>UR5 Robot Description (ROS2 Jazzy — Refueling Project)</description>
  <maintainer email="user@todo.todo">Anurag Shetye</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>urdf</depend>
  <depend>xacro</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
